Add RXOR and XNOR Experiments
neurodata/SDTF pull request #30
Opened 2021-11-12 21:52 UTC by nhahn7

Added two XOR streaming benchmark experiments to compare SDT/SDF performance against Mondrian Forest and Hoeffding Tree. 
- r_xor.py runs the RXOR experiment 
- xor.py runs the XNOR experiment 
- xor_functions.py includes functions used by both experiments and the Jupyter Notebook
- xor_experiments.ipynb plots data/results 
- results are stored in benchmarks/results

2021-11-12 23:49 UTC, PSSF23 requested changes
Overall, good job! All you need to do is to `black` format your notebook. After merging I might do some minor changes on text.

Remember to pull my changes before committing!

2021-11-13 02:16 UTC, nhahn7 commented
@PSSF23 I seem to be having some issues with black formatting using https://github.com/csurfer/blackcellmagic. Do you have a recommendation for what to use?

2021-11-13 02:21 UTC, PSSF23 commented
@nhahn7 Don't use those anymore, `black` officially supports `jupyter` notebooks now. Just `pip install black[jupyter]`.

2021-11-13 02:47 UTC, nhahn7 commented
@PSSF23 that seems to have fixed it. Thanks

2021-11-13 02:49 UTC, PSSF23 approved these changes
great!

2021-11-13 02:49 UTC, merged